### ISSUE TITLE
How to deploy open loyalty framework backend

### ISSUE THREAD

**Issue by tharun148** [DivanteLtd/open-loyalty-framework#2]
Hi, 
I need to deploy this on apache2 server. After I deployed login API returns the token. but other API's return 401 here is the link my .htaccess and virtual host files [https://github.com/lexik/LexikJWTAuthenticationBundle/issues/452](https://github.com/lexik/LexikJWTAuthenticationBundle/issues/452)

**Comment by tjurczak** [comment]
hI @tharun148,

I see that your problem was related to apache/nginx (and has been closed). Is it still active?
